import { Job } from './collection';

export const sampleJobs: Job[] = [
  {
    title: 'Pipeline Technician',
    company: 'Keystone Energy',
    location: 'Scranton, PA',
    basePay: 22,
    payMax: 28,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['pipeline', 'maintenance', 'field'],
    benefits: ['Health Insurance', '401k', 'Paid Training'],
    description:
      'Maintain and inspect natural gas pipeline systems. Work with field teams to ensure safe energy delivery.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
  {
    title: 'Electrical Supervisor',
    company: 'Northeast Power Systems',
    location: 'Wilkes-Barre, PA',
    basePay: 35,
    payMax: 45,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['electrical', 'supervisor', 'industrial'],
    benefits: ['Health Insurance', '401k', 'Company Truck'],
    description:
      'Supervise electrical crews on commercial job sites. Ensure projects meet safety and quality standards.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
  {
    title: 'Safety Inspector',
    company: 'Tri-State Safety Group',
    location: 'Hazleton, PA',
    basePay: 28,
    payMax: 35,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['safety', 'inspection', 'compliance'],
    benefits: ['Flexible Schedule', 'Travel Reimbursement'],
    description:
      'Conduct safety inspections across multiple industrial facilities. Identify hazards and recommend corrective actions.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
  {
    title: 'Equipment Operator',
    company: 'Mountain Construction',
    location: 'Stroudsburg, PA',
    basePay: 18,
    payMax: 25,
    payUnit: 'hourly',
    jobType: 'part-time',
    tags: ['equipment', 'construction', 'operator'],
    benefits: ['Paid Training', 'Flexible Hours'],
    description:
      'Operate construction machinery on active job sites. Assist crews with excavation and site preparation.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
  {
    title: 'HVAC Technician',
    company: 'Lehigh Valley Mechanical',
    location: 'Allentown, PA',
    basePay: 30,
    payMax: 40,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['hvac', 'repair', 'installation'],
    benefits: ['Health Insurance', '401k', 'Paid Vacation'],
    description:
      'Install and repair HVAC systems for residential and commercial clients. Diagnose system issues and perform preventative maintenance.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
  {
    title: 'Field Engineer',
    company: 'Atlantic Infrastructure',
    location: 'Bethlehem, PA',
    basePay: 45,
    payMax: 60,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['engineering', 'fieldwork', 'construction'],
    benefits: ['Health Insurance', '401k', 'Performance Bonus'],
    description:
      'Provide engineering support on infrastructure projects. Coordinate with contractors and ensure technical specifications are met.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date(),
    isActive: true,
  },
];
