import { Job } from './collection';

export const sampleJobs: Omit<Job, '_id'>[] = [
  // ── Pipeline / Oil & Gas ──────────────────────────────────────────────────
  {
    title: 'Pipeline Technician',
    company: 'Keystone Energy',
    location: 'Scranton, PA',
    basePay: 22,
    payMax: 28,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['pipeline', 'maintenance', 'field'],
    benefits: ['Health Insurance', '401k', 'Paid Training'],
    description:
      'Maintain and inspect natural gas pipeline systems. Work with field teams to ensure safe energy delivery across northeastern Pennsylvania.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-02-10'),
    isActive: true,
  },
  {
    title: 'Pipeline Inspector',
    company: 'Summit Gas Services',
    location: 'Pittsburgh, PA',
    basePay: 30,
    payMax: 38,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['pipeline', 'inspection', 'oil-and-gas'],
    benefits: ['Per Diem', 'Travel Reimbursement', 'Tool Allowance'],
    description:
      'Perform in-line inspections and integrity assessments on high-pressure natural gas transmission lines. Coordinate findings with engineering teams.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-01'),
    isActive: true,
  },
  {
    title: 'Compression Operator',
    company: 'Appalachian Midstream Partners',
    location: 'Morgantown, WV',
    basePay: 28,
    payMax: 35,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['compression', 'oil-and-gas', 'operations'],
    benefits: ['Health Insurance', '401k', 'Overtime Available'],
    description:
      'Monitor and operate natural gas compressor stations. Perform routine maintenance, troubleshoot equipment failures, and maintain operational logs.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-28'),
    isActive: true,
  },
  {
    title: 'Instrumentation Technician',
    company: 'Marcellus Energy Solutions',
    location: 'Canonsburg, PA',
    basePay: 32,
    payMax: 42,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['instrumentation', 'controls', 'oil-and-gas'],
    benefits: ['Health Insurance', '401k', 'Tuition Reimbursement'],
    description:
      'Install, calibrate, and maintain instrumentation and control systems for natural gas gathering and processing facilities.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-10'),
    isActive: true,
  },

  // ── Electrical ────────────────────────────────────────────────────────────
  {
    title: 'Electrical Supervisor',
    company: 'Northeast Power Systems',
    location: 'Wilkes-Barre, PA',
    basePay: 35,
    payMax: 45,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['electrical', 'supervisor', 'industrial'],
    benefits: ['Health Insurance', '401k', 'Company Truck'],
    description:
      'Supervise electrical crews on commercial job sites. Ensure projects meet safety and quality standards.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-02-14'),
    isActive: true,
  },
  {
    title: 'Journeyman Electrician',
    company: 'Tri-State Electric',
    location: 'Philadelphia, PA',
    basePay: 38,
    payMax: 48,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['electrical', 'journeyman', 'commercial'],
    benefits: ['Union Benefits', 'Health Insurance', 'Pension'],
    description:
      'Perform electrical installations on large commercial and industrial projects. Read blueprints, run conduit, and terminate panels.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-15'),
    isActive: true,
  },
  {
    title: 'Apprentice Electrician',
    company: 'Tri-State Electric',
    location: 'Philadelphia, PA',
    basePay: 22,
    payMax: 28,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['electrical', 'apprentice', 'entry-level'],
    benefits: ['Union Benefits', 'Paid Training', 'Tool Allowance'],
    description:
      'Join a union electrical apprenticeship program. Work alongside journeymen and foremen on commercial and industrial projects while earning your license.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-20'),
    isActive: true,
  },
  {
    title: 'Substation Technician',
    company: 'GridPower Utilities',
    location: 'Harrisburg, PA',
    basePay: 40,
    payMax: 52,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['electrical', 'substation', 'utilities'],
    benefits: ['Health Insurance', 'Pension', 'Paid Overtime'],
    description:
      'Maintain and test high-voltage substation equipment including transformers, circuit breakers, and relay protection systems.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-18'),
    isActive: true,
  },

  // ── Safety ─────────────────────────────────────────────────────────────────
  {
    title: 'Safety Inspector',
    company: 'Tri-State Safety Group',
    location: 'Hazleton, PA',
    basePay: 28,
    payMax: 35,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['safety', 'inspection', 'compliance'],
    benefits: ['Flexible Schedule', 'Travel Reimbursement'],
    description:
      'Conduct safety inspections across multiple industrial facilities. Identify hazards and recommend corrective actions.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-02-20'),
    isActive: true,
  },
  {
    title: 'HSE Manager',
    company: 'Atlantic Infrastructure',
    location: 'Allentown, PA',
    basePay: 80000,
    payMax: 100000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['safety', 'HSE', 'management', 'compliance'],
    benefits: ['Health Insurance', '401k', 'Company Vehicle', 'Bonus Eligible'],
    description:
      'Oversee all health, safety, and environmental programs for a large infrastructure contractor. Develop policies, conduct audits, and lead incident investigations.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-05'),
    isActive: true,
  },

  // ── Construction ───────────────────────────────────────────────────────────
  {
    title: 'Equipment Operator',
    company: 'Mountain Construction',
    location: 'Stroudsburg, PA',
    basePay: 18,
    payMax: 25,
    payUnit: 'hourly',
    jobType: 'part-time',
    tags: ['equipment', 'construction', 'operator'],
    benefits: ['Paid Training', 'Flexible Hours'],
    description:
      'Operate construction machinery on active job sites. Assist crews with excavation and site preparation.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-02-25'),
    isActive: true,
  },
  {
    title: 'General Laborer',
    company: 'ProBuild Contractors',
    location: 'Reading, PA',
    basePay: 18,
    payMax: 22,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['laborer', 'construction', 'entry-level'],
    benefits: ['Paid Training', 'Overtime Available'],
    description:
      'Support construction crews with material handling, site cleanup, and basic tasks. No experience required — on-the-job training provided.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-22'),
    isActive: true,
  },
  {
    title: 'Ironworker',
    company: 'SteelForm Erectors',
    location: 'Pittsburgh, PA',
    basePay: 34,
    payMax: 44,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['ironwork', 'structural', 'construction'],
    benefits: ['Union Benefits', 'Health Insurance', 'Pension'],
    description:
      'Erect structural steel frameworks for bridges, buildings, and industrial plants. Experience with rigging, bolting, and welding preferred.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-10'),
    isActive: true,
  },
  {
    title: 'Concrete Finisher',
    company: 'Keystone Flatwork',
    location: 'Lancaster, PA',
    basePay: 24,
    payMax: 32,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['concrete', 'construction', 'finishing'],
    benefits: ['Overtime Available', 'Tool Allowance'],
    description:
      'Finish concrete surfaces for commercial floors, sidewalks, and foundations. Trowel, screed, and stamp concrete to specification.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-08'),
    isActive: true,
  },
  {
    title: 'Carpenter',
    company: 'Eastside Builders',
    location: 'Allentown, PA',
    basePay: 26,
    payMax: 36,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['carpentry', 'framing', 'construction'],
    benefits: ['Health Insurance', 'Paid Vacation', 'Tool Allowance'],
    description:
      'Frame residential and light commercial structures. Read blueprints, cut and assemble lumber, and install doors and windows.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-12'),
    isActive: true,
  },

  // ── HVAC / Mechanical ─────────────────────────────────────────────────────
  {
    title: 'HVAC Technician',
    company: 'Lehigh Valley Mechanical',
    location: 'Allentown, PA',
    basePay: 30,
    payMax: 40,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['hvac', 'repair', 'installation'],
    benefits: ['Health Insurance', '401k', 'Paid Vacation'],
    description:
      'Install and repair HVAC systems for residential and commercial clients. Diagnose system issues and perform preventative maintenance.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-01'),
    isActive: true,
  },
  {
    title: 'Refrigeration Mechanic',
    company: 'CoolSystems PA',
    location: 'Erie, PA',
    basePay: 28,
    payMax: 38,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['refrigeration', 'hvac', 'mechanical'],
    benefits: ['Health Insurance', '401k', 'Company Van'],
    description:
      'Service commercial refrigeration systems including walk-in coolers, display cases, and ice machines. EPA 608 certification required.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-25'),
    isActive: true,
  },
  {
    title: 'Pipefitter',
    company: 'Advantage Mechanical',
    location: 'Bethlehem, PA',
    basePay: 32,
    payMax: 42,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['pipefitting', 'plumbing', 'industrial'],
    benefits: ['Union Benefits', 'Health Insurance', 'Pension'],
    description:
      'Lay out, fabricate, and install pipe systems for industrial facilities. Work includes steam, process, and HVAC piping from prints.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-15'),
    isActive: true,
  },

  // ── Engineering / Management ───────────────────────────────────────────────
  {
    title: 'Field Engineer',
    company: 'Atlantic Infrastructure',
    location: 'Bethlehem, PA',
    basePay: 45,
    payMax: 60,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['engineering', 'fieldwork', 'construction'],
    benefits: ['Health Insurance', '401k', 'Performance Bonus'],
    description:
      'Provide engineering support on infrastructure projects. Coordinate with contractors and ensure technical specifications are met.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-03-05'),
    isActive: true,
  },
  {
    title: 'Project Manager – Civil',
    company: 'Keystone Development Group',
    location: 'Philadelphia, PA',
    basePay: 90000,
    payMax: 120000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['project-management', 'civil', 'construction'],
    benefits: ['Health Insurance', '401k', 'Bonus', 'Remote Flexibility'],
    description:
      'Manage civil construction projects from pre-construction through closeout. Oversee scheduling, budget, subcontractors, and client communication.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-03'),
    isActive: true,
  },
  {
    title: 'Estimator – Industrial',
    company: 'Penn Industrial Services',
    location: 'Harrisburg, PA',
    basePay: 70000,
    payMax: 90000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['estimating', 'industrial', 'bidding'],
    benefits: ['Health Insurance', '401k', 'Flexible Schedule'],
    description:
      'Prepare detailed cost estimates for industrial construction and maintenance projects. Analyze bid documents, solicit subcontractor quotes, and support proposal development.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-17'),
    isActive: true,
  },

  // ── Welding ────────────────────────────────────────────────────────────────
  {
    title: 'Certified Welder',
    company: 'Blue Mountain Fabrication',
    location: 'Pottsville, PA',
    basePay: 28,
    payMax: 38,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['welding', 'fabrication', 'MIG', 'TIG'],
    benefits: ['Health Insurance', 'Paid Vacation', 'Tool Allowance'],
    description:
      'Perform MIG, TIG, and stick welding on structural and pipe applications. Read weld symbols from blueprints and maintain quality to AWS standards.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-19'),
    isActive: true,
  },
  {
    title: 'Pipe Welder',
    company: 'Summit Gas Services',
    location: 'Pittsburgh, PA',
    basePay: 35,
    payMax: 48,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['welding', 'pipeline', 'oil-and-gas'],
    benefits: ['Per Diem', 'Travel Reimbursement', 'Overtime Available'],
    description:
      'Weld high-pressure natural gas pipeline joints in the field. ASME B31.8 or API 1104 certification preferred. Must pass weld test on hire.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-14'),
    isActive: true,
  },

  // ── CDL / Driving ──────────────────────────────────────────────────────────
  {
    title: 'CDL-A Truck Driver',
    company: 'Keystone Energy',
    location: 'Scranton, PA',
    basePay: 26,
    payMax: 32,
    payUnit: 'hourly',
    jobType: 'full-time',
    tags: ['CDL', 'driving', 'logistics'],
    benefits: ['Health Insurance', '401k', 'Sign-On Bonus'],
    description:
      'Haul equipment and materials to energy job sites across the region. Local and regional routes. Home most nights. CDL-A with clean MVR required.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-06'),
    isActive: true,
  },

  // ── Part-time / Flexible ───────────────────────────────────────────────────
  {
    title: 'Meter Reader',
    company: 'GridPower Utilities',
    location: 'Harrisburg, PA',
    basePay: 18,
    payMax: 22,
    payUnit: 'hourly',
    jobType: 'part-time',
    tags: ['utilities', 'meter-reading', 'fieldwork'],
    benefits: ['Flexible Hours', 'Mileage Reimbursement'],
    description:
      'Read residential and commercial utility meters along assigned routes. Accurately record data and report any hazards or equipment issues.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-24'),
    isActive: true,
  },
  {
    title: 'Maintenance Technician',
    company: 'Valley Industrial Park',
    location: 'Altoona, PA',
    basePay: 20,
    payMax: 26,
    payUnit: 'hourly',
    jobType: 'part-time',
    tags: ['maintenance', 'facilities', 'industrial'],
    benefits: ['Flexible Hours', 'Overtime Eligible'],
    description:
      'Perform general building and equipment maintenance for a multi-tenant industrial park. Tasks include plumbing repairs, lighting, HVAC filters, and grounds upkeep.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-26'),
    isActive: true,
  },

  // ── Software Engineering ───────────────────────────────────────────────────
  {
    title: 'Full-Stack Software Engineer',
    company: 'Hybrid Hiring Technologies',
    location: 'Remote',
    basePay: 110000,
    payMax: 140000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['software', 'full-stack', 'react', 'node'],
    benefits: ['Health Insurance', '401k', 'Remote Work', 'Home Office Stipend'],
    description:
      'Build and maintain web applications using React, Node.js, and MongoDB. Collaborate with product and design teams to ship features end-to-end. Experience with REST APIs and CI/CD pipelines required.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-28'),
    isActive: true,
  },
  {
    title: 'Frontend Engineer',
    company: 'ClearPath Digital',
    location: 'Philadelphia, PA',
    basePay: 95000,
    payMax: 125000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['software', 'frontend', 'react', 'typescript'],
    benefits: ['Health Insurance', '401k', 'Hybrid Schedule', 'Learning Budget'],
    description:
      'Own the frontend of a B2B SaaS platform. Write clean, accessible React and TypeScript, collaborate closely with designers, and maintain a high-quality component library.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-01'),
    isActive: true,
  },
  {
    title: 'Backend Engineer',
    company: 'GridPoint Analytics',
    location: 'Pittsburgh, PA',
    basePay: 105000,
    payMax: 135000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['software', 'backend', 'node', 'postgresql'],
    benefits: ['Health Insurance', '401k', 'Hybrid Schedule', 'Equity'],
    description:
      'Design and build scalable APIs and data pipelines for an energy analytics platform. Experience with Node.js, PostgreSQL, and cloud infrastructure (AWS or GCP) required.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-30'),
    isActive: true,
  },
  {
    title: 'Mobile Engineer (React Native)',
    company: 'TradeForce',
    location: 'Remote',
    basePay: 100000,
    payMax: 130000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['software', 'mobile', 'react-native', 'ios', 'android'],
    benefits: ['Health Insurance', '401k', 'Fully Remote', 'Equipment Stipend'],
    description:
      'Build and ship cross-platform mobile features for a trades-focused workforce app. Solid React Native skills required; experience with Expo and push notifications is a plus.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-02'),
    isActive: true,
  },
  {
    title: 'Software Engineer – Contract',
    company: 'Penn State Industries',
    location: 'Greenville, SC',
    basePay: 75,
    payMax: 95,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['software', 'contract', 'full-stack', 'javascript'],
    benefits: ['Flexible Hours', 'Remote Options'],
    description:
      'Short-term contract (3–6 months) to help modernize an internal operations tool. Full-stack JavaScript experience required. Must be available to work on-site periodically.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-03'),
    isActive: true,
  },
  {
    title: 'DevOps Engineer',
    company: 'Keystone Development Group',
    location: 'Philadelphia, PA',
    basePay: 115000,
    payMax: 145000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['devops', 'software', 'aws', 'kubernetes', 'ci-cd'],
    benefits: ['Health Insurance', '401k', 'Hybrid Schedule', 'Bonus'],
    description:
      'Own infrastructure and deployment pipelines for a growing SaaS platform. Experience with AWS, Terraform, Docker, and Kubernetes required. On-call rotation included.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-29'),
    isActive: true,
  },
  {
    title: 'Junior Software Engineer',
    company: 'Hybrid Hiring Technologies',
    location: 'Remote',
    basePay: 70000,
    payMax: 90000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['software', 'junior', 'entry-level', 'react', 'javascript'],
    benefits: ['Health Insurance', '401k', 'Remote Work', 'Mentorship Program'],
    description:
      'A great first role for a bootcamp or CS grad looking to grow. You will work alongside senior engineers to build features, fix bugs, and learn engineering best practices in a real production codebase.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-04'),
    isActive: true,
  },

  // ── Product Design ─────────────────────────────────────────────────────────
  {
    title: 'Product Designer',
    company: 'ClearPath Digital',
    location: 'Philadelphia, PA',
    basePay: 95000,
    payMax: 120000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['design', 'product-design', 'figma', 'ux'],
    benefits: ['Health Insurance', '401k', 'Hybrid Schedule', 'Learning Budget'],
    description:
      'Own end-to-end product design for a B2B SaaS platform. Conduct user research, create wireframes and high-fidelity mockups in Figma, and collaborate with engineering to ship polished experiences.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-01'),
    isActive: true,
  },
  {
    title: 'UX Designer',
    company: 'TradeForce',
    location: 'Remote',
    basePay: 85000,
    payMax: 110000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['design', 'ux', 'figma', 'user-research'],
    benefits: ['Health Insurance', '401k', 'Fully Remote', 'Equipment Stipend'],
    description:
      'Define user flows, run usability tests, and design intuitive interfaces for a mobile-first workforce platform serving tradespeople. Figma proficiency and a strong research background required.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-02'),
    isActive: true,
  },
  {
    title: 'UI/UX Designer – Contract',
    company: 'Penn State Industries',
    location: 'Greenville, SC',
    basePay: 55,
    payMax: 75,
    payUnit: 'hourly',
    jobType: 'contract',
    tags: ['design', 'ui', 'ux', 'figma', 'contract'],
    benefits: ['Flexible Hours', 'Remote Options'],
    description:
      'Six-month contract to redesign a legacy internal dashboard. Deliverables include user research, a Figma design system, and handoff-ready specs for the engineering team.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-05-03'),
    isActive: true,
  },
  {
    title: 'Senior Product Designer',
    company: 'GridPoint Analytics',
    location: 'Pittsburgh, PA',
    basePay: 115000,
    payMax: 145000,
    payUnit: 'salary',
    jobType: 'full-time',
    tags: ['design', 'product-design', 'senior', 'figma', 'design-systems'],
    benefits: ['Health Insurance', '401k', 'Hybrid Schedule', 'Equity'],
    description:
      'Lead design for a complex data visualization product used by energy companies. You will define design strategy, maintain a Figma design system, mentor junior designers, and partner directly with the VP of Product.',
    externalApplyUrl: 'https://example.com/apply',
    postedAt: new Date('2026-04-30'),
    isActive: true,
  },
];
